### ISSUE TITLE
More Maintainers wanted!

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-play-json#1]
Please comment if you are interested in helping to maintain this module :) Thanks!

**Comment by henricook** [comment]
@armanbilge What do you think the main challenges are here for a new maintainer? Do any _big changes_ immediately spring to mind?

**Comment by armanbilge** [comment]
@henricook 

> Do any _big changes_ immediately spring to mind?

Hmm, possibly Scala 3 support? Not sure what the upstream situation is with that.

Also maintaining support for http4s 1.x (and its milestones) since those are breaking changes.

---

> What do you think the main challenges are here for a new maintainer?

Keeping up with the two upstreams. On the Play JSON side, I have no idea how often they make releases that require changes here. Probably not too often?

For http4s, 0.23.x is stable, but 1.x milestones can have significant breaking changes. If you have the time and motivation to keep up with milestones, awesome, otherwise I think it's fine to backburner it (very few / no repos are working that hard to keep pace).

---

> Also as a maintainer do you have any download/usage stats for this project?

Unfortunately I don't have sonatype publishing rights for `org.http4s` so I can see these stats actually.

> I'd imagine a strong closed source/enterprise usage.

Quite possibly, and Sonatype stats often measure this well because of intermediate artifactories that only require a single internal download.

**Comment by henricook** [comment]
@armanbilge I'd be willing to take this on. If that sounds fine to you let me know what happens next, or we can chat on discord.

I use http4s-play-json in my day to day on Scala 2.13 but also have a scala 3 migration planned in the next few months so it feels like a good fit.

**Comment by matmannion** [comment]
Happy to volunteer as an additional maintainer here, I work on some of the same projects as Henri but also some diverging ones so suspect it will help with coverage in enterprise projects.

**Comment by henricook** [comment]
SGTM @armanbilge

**Comment by armanbilge** [comment]
I added Mat, thanks for stepping up! If you two are happy feel free to close this issue :)

I'm going to unsubscribe from regular notifications on this repo, but don't hesitate to ping me if you need help with something!

**Comment by henricook** [comment]
Thanks so much @armanbilge
