### ISSUE TITLE
jsonOf should include JSON errors in the message

### ISSUE THREAD

**Issue by matmannion** [http4s/http4s-play-json#81]
```scala
  def jsonOf[F[_]: Concurrent, A](implicit decoder: Reads[A]): EntityDecoder[F, A] =
    jsonDecoder[F].flatMapR { json =>
      decoder
        .reads(json)
        .fold(
          _ =>
            DecodeResult.failureT(InvalidMessageBodyFailure(s"Could not decode JSON: $json", None)),
          DecodeResult.successT(_),
        )
    }
```

This swallows the error case of the fold which includes the JSON decoding error details.

**Comment by henricook** [comment]
Good catch. I think the circe decoder fixes this, so we can probably do something very similar: https://github.com/http4s/http4s/blob/series/0.23/circe/src/main/scala/org/http4s/circe/CirceInstances.scala#L115
